---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../components/app
namespace: "jellyseerr"
namePrefix: "jellyseerr-"
images:
  - name: "fallenbagel/jellyseerr"
    newTag: "1.5.0"
configMapGenerator:
  - name: app-config
    envs:
      - "app_config.env"
